In [24]:
from Common.FunctionHandle import inputInt

# 1. Giới thiệu Dataframe

In [72]:
import pandas as pd

In [26]:
score = {
    "name": ['Ray','Japhy','Zosa'],
    "city": ['San Francisco','San Francisco','Denver'],
    "score": [75,92,94]
}

In [27]:
df1 = pd.DataFrame(score)
df1["city"] #type Series
df1[["city"]] #type Dataframe

            city
0  San Francisco
1  San Francisco
2         Denver

In [28]:
df1['name_city'] = df1['name']+'_'+df1['city']
df1

    name           city  score            name_city
0    Ray  San Francisco     75    Ray_San Francisco
1  Japhy  San Francisco     92  Japhy_San Francisco
2   Zosa         Denver     94          Zosa_Denver

In [29]:
#fiter data
threshold = 80 
df1[df1['score'] >= threshold]

    name           city  score            name_city
1  Japhy  San Francisco     92  Japhy_San Francisco
2   Zosa         Denver     94          Zosa_Denver

# II.Truyền data vào dataframe từ file csv (quan trọng)

In [30]:
#1. Đọc file từ csv
iris = pd.read_csv('RawData/iris.csv')
iris.head(5) #lấy 5 dòng đầu
iris.tail(5) #lấy 5 dòng cuối

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [31]:
#Đêm DF có bao nhiêu dòng, cột
iris.shape
#type
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [32]:
#Định vị các cell trong DataFrame
iris.loc[147,'petal_width'] #index, tên cột

np.float64(2.0)

In [33]:
#đặt index theo cột
iris2= iris.set_index("species")
iris2

           sepal_length  sepal_width  petal_length  petal_width
species
setosa              5.1          3.5           1.4          0.2
setosa              4.9          3.0           1.4          0.2
setosa              4.7          3.2           1.3          0.2
setosa              4.6          3.1           1.5          0.2
setosa              5.0          3.6           1.4          0.2
...                 ...          ...           ...          ...
virginica           6.7          3.0           5.2          2.3
virginica           6.3          2.5           5.0          1.9
virginica           6.5          3.0           5.2          2.0
virginica           6.2          3.4           5.4          2.3
virginica           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# Lấy ra số liệu của loài setosa
iris2.loc['setosa','sepal_length']

In [35]:
#Iloc: interger location
iris.iloc[2,1]

np.float64(3.2)

In [36]:
#Xuất file csv
iris2.to_csv('output_iris.csv',index=True) #index = True => đem cột index để ở đầu tiên

# **III.Pandas Option**

In [ ]:

pd.set_option("display.max_rows", 2)

pd.set_option("display.max_columns", 2)
pd.options.display.float_format - '{}:,2f'.format
# : là số truyền vào
# ,: là ngăn cách hàng ngàn
# .: thể hiện hàng thập phân
# 2f: lấy 2 chứ số thập phân

# **IV. Data Types**

In [ ]:
planets = pd.read_csv('RawData/planets.csv')
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [ ]:
planets['year'] = planets['year'].astype('str')

In [ ]:
planets.mean(numeric_only=True)

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
dtype: float64

In [ ]:
planets['year_dt'] = pd.to_datetime(planets['year'],format='%Y')
planets

,method,number,orbital_period,mass,distance,year,year_dt
0,Radial Velocity,1,269.300000,7.10,77.40,2006,2006-01-01
1,Radial Velocity,1,874.774000,2.21,56.95,2008,2008-01-01
2,Radial Velocity,1,763.000000,2.60,19.84,2011,2011-01-01
3,Radial Velocity,1,326.030000,19.40,110.62,2007,2007-01-01
4,Radial Velocity,1,516.220000,10.50,119.47,2009,2009-01-01
...,...,...,...,...,...,...,...
1030,Transit,1,3.941507,NaN,172.00,2006,2006-01-01
1031,Transit,1,2.615864,NaN,148.00,2007,2007-01-01
1032,Transit,1,3.191524,NaN,174.00,2007,2007-01-01
1033,Transit,1,4.125083,NaN,293.00,2008,2008-01-01
1034,Transit,1,4.187757,NaN,260.00,2008,2008-01-01

# **V. Type String in Series**

In [49]:
names = pd.Series(['Pomeray, CODY ',' Wagner; Jarry','smith, Ray'])
names = names.astype("string")
names

0    Pomeray, CODY
1     Wagner; Jarry
2        smith, Ray
dtype: string

In [50]:
names= names.str.replace(";",",")
names

0    Pomeray, CODY
1     Wagner, Jarry
2        smith, Ray
dtype: string

In [51]:
#Lấy độ dài
names.str.len()

0    14
1    14
2    10
dtype: Int64

In [52]:
#Bỏ khoản trắng đầu đuôi
names = names.str.strip()
names

0    Pomeray, CODY
1    Wagner, Jarry
2       smith, Ray
dtype: string

In [53]:
#Viết Hoa all
names.str.upper()
names.str.lower()

0    pomeray, cody
1    wagner, jarry
2       smith, ray
dtype: string

In [54]:
# pomeray, cody => [pomeray, cody]
#Xác định dấu hiện phân cách (delimiter) ', '
names = names.str.split(', ')

In [56]:
#Đảo chuỗi
names = pd.Series([i[::-1] for i in names])
names = [' '.join(i) for i  in names]
names

['Pomeray CODY', 'Wagner Jarry', 'smith Ray']

# **VI. Date Type in Pandas**

In [63]:
dateR = pd.period_range('01/01/2026',freq='30d',periods=6)
dateR

PeriodIndex(['2026-01-01', '2026-01-31', '2026-03-02', '2026-04-01',
             '2026-05-01', '2026-05-31'],
            dtype='period[30D]')

In [ ]:
#Lấy ngày đầu tiên
dateR.min()

Period('2026-01-01', '30D')

In [ ]:
#Lấy ngày gần nhất
dateR.max()

Period('2026-05-31', '30D')

In [64]:
#Biến thành Dataqframe:
date_df = pd.DataFrame(data=dateR,columns=['sample_date'])
date_df

  sample_date
0  2026-01-01
1  2026-01-31
2  2026-03-02
3  2026-04-01
4  2026-05-01
5  2026-05-31

In [65]:
#Lấy ngày trước và sau của ô hiện tại
date_df['prev_date'] = date_df['sample_date'].shift(periods=1)
date_df

  sample_date   prev_date
0  2026-01-01         NaT
1  2026-01-31  2026-01-01
2  2026-03-02  2026-01-31
3  2026-04-01  2026-03-02
4  2026-05-01  2026-04-01
5  2026-05-31  2026-05-01

In [66]:
date_df['next_date'] = date_df['sample_date'].shift(periods=-1)
date_df

  sample_date   prev_date   next_date
0  2026-01-01         NaT  2026-01-31
1  2026-01-31  2026-01-01  2026-03-02
2  2026-03-02  2026-01-31  2026-04-01
3  2026-04-01  2026-03-02  2026-05-01
4  2026-05-01  2026-04-01  2026-05-31
5  2026-05-31  2026-05-01         NaT

In [69]:
#Cách 1
date_df['diff_date'] = date_df['next_date'] - date_df['sample_date']
#Cách 2
date_df["date_diff"] = date_df["sample_date"].diff(periods=1)

date_df

c:\Users\sangt\anaconda3\Lib\site-packages\pandas\core\arrays\datetimelike.py:1329: RuntimeWarning: overflow encountered in scalar multiply
  new_data = np.array([self.freq.base * x for x in new_i8_data])

  sample_date   prev_date   next_date    diff_date    date_diff
0  2026-01-01         NaT  2026-01-31  <30 * Days>          NaT
1  2026-01-31  2026-01-01  2026-03-02  <30 * Days>  <30 * Days>
2  2026-03-02  2026-01-31  2026-04-01  <30 * Days>  <30 * Days>
3  2026-04-01  2026-03-02  2026-05-01  <30 * Days>  <30 * Days>
4  2026-05-01  2026-04-01  2026-05-31  <30 * Days>  <30 * Days>
5  2026-05-31  2026-05-01         NaT          NaT  <30 * Days>

In [70]:
#Tìm ngày đầu tiên trong tháng
date_df['fist_day_month'] = date_df['sample_date'].values.astype("datetime64[M]")
date_df

  sample_date   prev_date   next_date    diff_date    date_diff fist_day_month
0  2026-01-01         NaT  2026-01-31  <30 * Days>          NaT     2026-01-01
1  2026-01-31  2026-01-01  2026-03-02  <30 * Days>  <30 * Days>     2026-01-01
2  2026-03-02  2026-01-31  2026-04-01  <30 * Days>  <30 * Days>     2026-03-01
3  2026-04-01  2026-03-02  2026-05-01  <30 * Days>  <30 * Days>     2026-04-01
4  2026-05-01  2026-04-01  2026-05-31  <30 * Days>  <30 * Days>     2026-05-01
5  2026-05-31  2026-05-01         NaT          NaT  <30 * Days>     2026-05-01

In [73]:
#Tìm thứ trong tuần:
date_df = pd.DataFrame(data=dateR,columns=['sample_date'])
date_df['sample_date'] = date_df['sample_date'].dt.to_timestamp()
date_df['sample_date'].dt.day_name()

0     Thursday
1     Saturday
2       Monday
3    Wednesday
4       Friday
5       Sunday
Name: sample_date, dtype: object