In [53]:
#trỏ tới common
import bootstrap
import pandas as pd
import numpy as np
from pathlib import Path
BASE_DIR = Path.cwd().parent
endPoin = f"{BASE_DIR}/RawData/File_BTVN/"

# **Yêu cầu 1: Đọc & làm sạch dữ liệu**

In [54]:
#Đọc cả 3 sheet bằng Pandas
from  Common.ClassHandleData import dataReader as dr
dfjson = dr.load(endPoin + "danso_khong_trung_tinh.xlsx")

#Chuẩn hóa tên tỉnh:
DanSoHienTai = dfjson["DanSoHienTai"]
DanSoHienTai["TinhThanh"] = DanSoHienTai["TinhThanh"].str.title()

DanSoNamTruoc = dfjson["DanSoNamTruoc"]
DanSoNamTruoc["TinhThanh"] = DanSoNamTruoc["TinhThanh"].str.title()

NhomHocVan = dfjson["NhomHocVan"]

# #Kiểm tra và chuyển cột số về kiểu int
# cols_Dsht = [
#     "DanSo (người)",
#     "DanSo_LaoDong (người)",
#     "ThatNghiep (người)"
# ]
# DanSoHienTai[cols_Dsht] = (
#     DanSoHienTai[cols_Dsht]
#         .apply(pd.to_numeric, errors="coerce")
#         .fillna(0)
#         .astype(int)
# )
# cols_Dsnt = [
#     "DanSo_NamTruoc (người)",
#     "LaoDong_NamTruoc (người)"
# ]
# DanSoNamTruoc[cols_Dsht] = (
#     DanSoNamTruoc[cols_Dsht]
#         .apply(pd.to_numeric, errors="coerce")
#         .fillna(0)
#         .astype(int)
# )
# cols_nhv = [
#     "TyLeViecLam (%)"
# ]
# NhomHocVan[cols_nhv] = (
#     NhomHocVan[cols_nhv]
#         .apply(pd.to_numeric, errors="coerce")
#         .fillna(0)
#         .astype(int)
# )

Đã đọc XML

# Yêu cầu 2: Gộp dữ liệu (Tạo ra cột mới)

In [55]:
#Gộp Sheet 1 và Sheet 2 theo TinhThanh
MergeData_TinhThanh = pd.merge(
    DanSoHienTai,
    DanSoNamTruoc,
    on="TinhThanh"
)
MergeData_TinhThanh

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người)
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228
...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570

In [ ]:
#Gộp thêm Sheet 3 theo HocVanPhoBien và Tạo bảng dữ liệu tổng hợp duy nhất
MergeDataTotal = pd.merge(
    MergeData_TinhThanh,
    NhomHocVan,
    left_on="HocVanPhoBien",
    right_on="HocVan",
    how="left"
).drop(columns="HocVan")
MergeDataTotal

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%)
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690,98
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478,98
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98
...,...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697,98
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716,88
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92

# Yêu cầu 3:  Tính toán & phân tích

In [57]:
#a) Tính tỷ lệ thất nghiệp (%) từng tỉnh:
MergeDataTotal["TyLeThatNghiep"] = (MergeDataTotal["ThatNghiep (người)"] / MergeDataTotal["DanSo_LaoDong (người)"]) * 100
MergeDataTotal

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690,98,2.360050
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478,98,2.648886
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95,1.417029
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95,1.560071
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98,2.712341
...,...,...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697,98,2.926431
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88,6.589281
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88,1.315901
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716,88,1.932926
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92,1.148798

In [58]:
#b) Phân loại mức thất nghiệp:

#cách 1:
# MergeDataTotal["PhanLoaiThatNghiep"] = pd.cut(
#     MergeDataTotal["TyLeThatNghiep"],
#     bins=[-np.inf, 2,4,6, np.inf],
#     labels=["Rất thấp", "Thấp", "Trung bình", "Cao"],
#     right=False
# )

#cách 2
def classify(rate):
    if rate < 2:
        return "Rất thấp"
    elif rate < 4:
        return "Thấp"
    elif rate < 6:
        return "Trung bình"
    else:
        return "Cao"

MergeDataTotal["PhanLoaiThatNghiep"] = MergeDataTotal["TyLeThatNghiep"].apply(classify)
MergeDataTotal

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690,98,2.360050,Thấp
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478,98,2.648886,Thấp
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95,1.417029,Rất thấp
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95,1.560071,Rất thấp
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98,2.712341,Thấp
...,...,...,...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697,98,2.926431,Thấp
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88,6.589281,Cao
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88,1.315901,Rất thấp
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716,88,1.932926,Rất thấp
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92,1.148798,Rất thấp

In [59]:
#c) Tính tăng trưởng dân số & lao động:
MergeDataTotal["TangDanSo"] = MergeDataTotal["DanSo (người)"] - MergeDataTotal["DanSo_NamTruoc (người)"]
MergeDataTotal["TangLaoDong"] = MergeDataTotal["DanSo_LaoDong (người)"] - MergeDataTotal["LaoDong_NamTruoc (người)"]
MergeDataTotal

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep,TangDanSo,TangLaoDong
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690,98,2.360050,Thấp,30434,5252
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478,98,2.648886,Thấp,31136,3654
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95,1.417029,Rất thấp,9472,5139
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95,1.560071,Rất thấp,27789,5823
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98,2.712341,Thấp,35817,1313
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697,98,2.926431,Thấp,12653,5824
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88,6.589281,Cao,34960,3555
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88,1.315901,Rất thấp,20394,22
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716,88,1.932926,Rất thấp,7378,4207
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92,1.148798,Rất thấp,22988,7684

In [60]:
#d) Xác định:
#10 tỉnh thất nghiệp cao nhất
result = (
    MergeDataTotal
    .sort_values(by="TyLeThatNghiep",ascending=False)
    .head(10)
)
result

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep,TangDanSo,TangLaoDong
24,Hà Giang,2395673,1415599,97670,Sau đại học,2363890,1408159,98,6.899553,Cao,31783,7440
13,Bình Định,3373677,1544055,106072,THPT,3358405,1538808,88,6.869703,Cao,15272,5247
30,Hưng Yên,11618349,6927285,469717,THPT,11617889,6924817,88,6.780680,Cao,460,2468
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88,6.589281,Cao,34960,3555
49,Quảng Trị,4783710,2735391,177994,Sau đại học,4751538,2735175,98,6.507077,Cao,32172,216
55,Thanh Hóa,11082341,6438264,416039,Cao đẳng,11078336,6433175,92,6.461975,Cao,4005,5089
36,Lào Cai,8183135,4994575,319958,THPT,8153530,4987910,88,6.406111,Cao,29605,6665
47,Quảng Ngãi,5765950,3020915,180355,Sau đại học,5764747,3015417,98,5.970211,Trung bình,1203,5498
50,Sóc Trăng,7044864,3554120,211339,THPT,7019636,3550707,88,5.946310,Trung bình,25228,3413
25,Hà Nam,5741264,2766879,159487,Cao đẳng,5727351,2761048,92,5.764148,Trung bình,13913,5831

In [61]:
#10 tỉnh thất nghiệp thấp nhất
result = (
    MergeDataTotal
    .sort_values(by="TyLeThatNghiep")
    .head(10)
)
result

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep,TangDanSo,TangLaoDong
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92,1.148798,Rất thấp,22988,7684
46,Quảng Nam,3711884,2135746,25003,Đại học,3706972,2131885,95,1.170692,Rất thấp,4912,3861
6,Bà Rịa - Vũng Tàu,6250465,3352885,40008,THPT,6227034,3348613,88,1.193241,Rất thấp,23431,4272
44,Phú Yên,2682210,1630255,19572,Cao đẳng,2655738,1630254,92,1.200548,Rất thấp,26472,1
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88,1.315901,Rất thấp,20394,22
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95,1.417029,Rất thấp,9472,5139
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95,1.560071,Rất thấp,27789,5823
56,Thừa Thiên Huế,4627433,2615354,45136,Sau đại học,4589840,2613895,98,1.725808,Rất thấp,37593,1459
22,Đồng Tháp,6860239,3509666,62840,Cao đẳng,6850569,3504938,92,1.790484,Rất thấp,9670,4728
53,Thái Bình,1079127,608082,11237,Đại học,1044011,605005,95,1.847942,Rất thấp,35116,3077

In [62]:
#10 tỉnh tăng dân số cao nhất
result = (
    MergeDataTotal
    .sort_values(by="TangDanSo",ascending=False)
    .head(10)
)
result

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep,TangDanSo,TangLaoDong
48,Quảng Ninh,11269215,6190965,126373,Đại học,11230238,6186183,95,2.041249,Thấp,38977,4782
54,Thái Nguyên,6347034,3028738,157235,Đại học,6308655,3028123,95,5.191436,Trung bình,38379,615
56,Thừa Thiên Huế,4627433,2615354,45136,Sau đại học,4589840,2613895,98,1.725808,Rất thấp,37593,1459
52,Tây Ninh,1212602,646901,17658,THPT,1175991,646066,88,2.729629,Thấp,36611,835
10,Bắc Ninh,5074556,2876114,155217,Cao đẳng,5038005,2875954,92,5.396761,Trung bình,36551,160
43,Phú Thọ,2498511,1622858,41029,Cao đẳng,2462163,1617462,92,2.528194,Thấp,36348,5396
39,Nam Định,7509065,4354244,146242,Sau đại học,7472784,4349118,98,3.358608,Thấp,36281,5126
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98,2.712341,Thấp,35817,1313
53,Thái Bình,1079127,608082,11237,Đại học,1044011,605005,95,1.847942,Rất thấp,35116,3077
34,Lai Châu,1317801,651803,29195,Cao đẳng,1282740,647457,92,4.479114,Trung bình,35061,4346

In [63]:
#e) Phân tích học vấn:
result = (
    MergeDataTotal["HocVanPhoBien"]
    .value_counts()
    .rename("SoTinh")
    .to_frame()
)

result["TyLe(%)"] = (
    MergeDataTotal["HocVanPhoBien"]
    .value_counts(normalize=True)
    * 100
).round(2)

result

               SoTinh  TyLe(%)
HocVanPhoBien
Sau đại học        18    28.57
Cao đẳng           17    26.98
Đại học            14    22.22
THPT               14    22.22

In [64]:
result = (
    MergeDataTotal
    .groupby("HocVanPhoBien")["TinhThanh"]
    .apply(list)
)

result

HocVanPhoBien
Cao đẳng       [Bắc Ninh, Bình Phước, Bình Thuận, Cao Bằng, Đ...
Sau đại học    [Hà Nội, Tp.Hcm, Cần Thơ, An Giang, Bắc Kạn, B...
THPT           [Bà Rịa - Vũng Tàu, Bắc Giang, Bình Định, Hậu ...
Đại học        [Đà Nẵng, Hải Phòng, Bình Dương, Đắk Lắk, Đắk ...
Name: TinhThanh, dtype: object

In [66]:
MergeDataTotal

,TinhThanh,DanSo (người),DanSo_LaoDong (người),ThatNghiep (người),HocVanPhoBien,DanSo_NamTruoc (người),LaoDong_NamTruoc (người),TyLeViecLam (%),TyLeThatNghiep,PhanLoaiThatNghiep,TangDanSo,TangLaoDong
0,Hà Nội,8568808,4724942,111511,Sau đại học,8538374,4719690,98,2.360050,Thấp,30434,5252
1,Tp.Hcm,10306537,6375132,168870,Sau đại học,10275401,6371478,98,2.648886,Thấp,31136,3654
2,Đà Nẵng,10903618,5916462,83838,Đại học,10894146,5911323,95,1.417029,Rất thấp,9472,5139
3,Hải Phòng,1464277,664521,10367,Đại học,1436488,658698,95,1.560071,Rất thấp,27789,5823
4,Cần Thơ,4677309,3009541,81629,Sau đại học,4641492,3008228,98,2.712341,Thấp,35817,1313
...,...,...,...,...,...,...,...,...,...,...,...,...
58,Trà Vinh,8850953,4176521,122223,Sau đại học,8838300,4170697,98,2.926431,Thấp,12653,5824
59,Tuyên Quang,4042627,2324715,153182,THPT,4007667,2321160,88,6.589281,Cao,34960,3555
60,Vĩnh Long,11326283,6551101,86206,THPT,11305889,6551079,88,1.315901,Rất thấp,20394,22
61,Vĩnh Phúc,6747777,3402923,65776,THPT,6740399,3398716,88,1.932926,Rất thấp,7378,4207
62,Yên Bái,10510280,5611254,64462,Cao đẳng,10487292,5603570,92,1.148798,Rất thấp,22988,7684

In [ ]:
#Học vấn phổ biến mang lại tỷ lệ việc làm cao nhất
result = (
    MergeDataTotal
    .assign( #dùng để thêm hoặc cập nhật cột mới trong DataFrame.
        TyLeViecLam=lambda df:
        (df["DanSo_LaoDong (người)"] - df["ThatNghiep (người)"])
        / df["DanSo_LaoDong (người)"] * 100
    )
    .groupby("HocVanPhoBien", as_index=False)["TyLeViecLam"]
    .mean()
    .sort_values("TyLeViecLam", ascending=False)
)

result

  HocVanPhoBien  TyLeViecLam
3       Đại học    96.779057
0      Cao đẳng    96.655218
1   Sau đại học    96.068765
2          THPT    95.735600

In [ ]:
result = (
    MergeDataTotal
    .assign( 
        TyLeViecLam=lambda df:
        (df["DanSo_LaoDong (người)"] - df["ThatNghiep (người)"])
        / df["DanSo_LaoDong (người)"] * 100
    )
    .groupby("HocVanPhoBien", as_index=False)["TyLeViecLam"]
    .mean()
    .nlargest(1, "TyLeViecLam") #nlargest(n, column) lấy n dòng có giá trị lớn nhất.
)

result

  HocVanPhoBien  TyLeViecLam
3       Đại học    96.779057