# Phân tích trạng thái kinh tế của các quốc gia
##### Author: Trần Hữu Sang
###### Note: tôi chọn dùng lạm phát, thất nghiệp, GDP làm biến đầu vào để đánh giá trạng thái kinh tế, không đủ để kết luận trực tiếp “khả năng phát triển kinh tế” của một quốc gia.
###### Source: https://www.macrotrends.net/

In [47]:
#%pip install -U undetected_chromedriver

In [48]:
import pandas as pd
import requests
from io import StringIO
import undetected_chromedriver as uc
from bs4 import BeautifulSoup
import time
UrlWeb = "https://www.macrotrends.net/global-metrics/countries/ranking"
Url_TyLeThatNghiep = "/unemployment-rate"
Url_TyLeLamPhat = "/inflation-rate-cpi"
Url_TangTruongGDP = "/gdp-growth-rate"
Url_GDPBinhQuan = "/gdp-per-capita"

In [49]:
def GetTableFromUrl(url, table_id="country_ranking"):
    driver = uc.Chrome(version_main=153)
    try:
        driver.get(UrlWeb + url)
        time.sleep(5)  # chờ Cloudflare verify + trang load xong

        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")
        table = soup.find("table", id=table_id)

        if table is None:
            print("Không tìm thấy bảng — có thể bị chặn bởi Cloudflare || id sai.")
            with open("debug.html", "w", encoding="utf-8") as f:
                f.write(html)
            return None

        df = pd.read_html(str(table))[0]
        return df
    finally:
        driver.quit()

#### **Set Dataframe**

In [ ]:
df_ThatNghiep = GetTableFromUrl(Url_TyLeThatNghiep)
df_ThatNghiep = df_ThatNghiep.melt(
    id_vars="Country Name",
    var_name="Year",
    value_name="Unemployment_Rate"
)
df_ThatNghiep

C:\Users\sang.th\AppData\Local\Temp\ipykernel_49820\2840444944.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

           Country Name  Year GDP_Per_Capita
0              Eswatini  2023         34.61%
1          South Africa  2023         32.10%
2              Djibouti  2023         26.07%
3              Botswana  2023         23.38%
4                 Gabon  2023         20.16%
..                  ...   ...            ...
930            Cambodia  2019          0.12%
931               Qatar  2019          0.10%
932  West Bank And Gaza  2019         25.34%
933               Sudan  2019         11.70%
934             Ukraine  2019          8.19%

[935 rows x 3 columns]

In [ ]:
df_LeLamPhat = GetTableFromUrl(Url_TyLeLamPhat)
df_LeLamPhat = df_LeLamPhat.melt(
    id_vars="Country Name",
    var_name="Year",
    value_name="Inflation_Rate_Cpi"
)
df_LeLamPhat

C:\Users\sang.th\AppData\Local\Temp\ipykernel_49820\2840444944.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

             Country Name  Year GDP_Per_Capita
0                 Lebanon  2023        221.34%
1               Argentina  2023        133.49%
2                  Turkey  2023         53.86%
3                Suriname  2023         51.59%
4            Sierra Leone  2023         47.64%
..                    ...   ...            ...
915              Eswatini  2019          2.60%
916  Syrian Arab Republic  2019         13.42%
917              Zimbabwe  2019        255.31%
918            Seychelles  2019          1.81%
919           Afghanistan  2019          2.30%

[920 rows x 3 columns]

In [ ]:
df_GDP_TT = GetTableFromUrl(Url_TangTruongGDP)
df_GDP_TT = df_GDP_TT.melt(
    id_vars="Country Name",
    var_name="Year",
    value_name="GDP_Growth_Rate"
)
df_GDP_TT

C:\Users\sang.th\AppData\Local\Temp\ipykernel_49820\2840444944.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

                  Country Name  Year GDP_Per_Capita
0                        Macao  2023         75.31%
1                       Guyana  2023         33.80%
2                        Samoa  2023         15.23%
3     Turks And Caicos Islands  2023         13.73%
4                        Malta  2023         10.63%
...                        ...   ...            ...
1045                   Estonia  2019          3.73%
1046          Marshall Islands  2019         10.45%
1047         Equatorial Guinea  2019         -5.48%
1048               Timor-Leste  2019         24.21%
1049                     Sudan  2019         -2.18%

[1050 rows x 3 columns]

In [53]:
df_GDP_BQ = GetTableFromUrl(Url_GDPBinhQuan)
df_GDP_BQ = df_GDP_BQ.melt(
    id_vars="Country Name",
    var_name="Year",
    value_name="GDP_Per_Capita"
)
df_GDP_BQ

C:\Users\sang.th\AppData\Local\Temp\ipykernel_49820\2840444944.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

                  Country Name  Year GDP_Per_Capita
0                       Monaco  2023       $256,800
1                Liechtenstein  2023       $206,781
2                   Luxembourg  2023       $133,231
3                      Bermuda  2023       $132,962
4                      Ireland  2023       $106,819
...                        ...   ...            ...
1045                      Guam  2019        $39,275
1046  St. Martin (French Part)  2019        $19,033
1047  Northern Mariana Islands  2019        $24,497
1048      Syrian Arab Republic  2019         $1,110
1049     Virgin Islands (U.S.)  2019        $38,634

[1050 rows x 3 columns]